Repository exasol/release-droid, pull requests merged in 2020-10, with the labels that each got.

#40 fix #37 refactor MavenPomParser
  src/main/java/com/exasol/repository/maven/MavenPomParser.java
Labels: refactoring

#41 #39: Disabled the GitHub issues check if the branch is not the defaul…
  doc/changes/changelog.md
  doc/changes/changes_0.2.0.md
  src/main/java/com/exasol/repository/AbstractGitHubGitBranchContent.java
  src/main/java/com/exasol/repository/GitBranchContent.java
  src/main/java/com/exasol/validation/GitHubPlatformValidator.java
  src/test/java/com/exasol/github/AbstractGitHubGitBranchContentTest.java
Labels: bug

#42 #35: Added validation that checks ".github/workflows/github_release.y…
  doc/changes/changes_0.2.0.md
  src/main/java/com/exasol/repository/AbstractGitHubGitBranchContent.java
  src/main/java/com/exasol/repository/GitBranchContent.java
  src/main/java/com/exasol/validation/GitHubPlatformValidator.java
  src/test/java/com/exasol/validation/GitHubPlatformValidatorTest.java
Labels: enhancement

#44 Enhamcement/43 use warning on date validation on branches
  doc/changes/changes_0.2.0.md
  src/main/java/com/exasol/github/GitHubPlatform.java
  src/main/java/com/exasol/validation/GitHubPlatformValidator.java
  src/main/java/com/exasol/validation/GitRepositoryValidator.java
  src/test/java/com/exasol/github/GitHubPlatformTest.java
  src/test/java/com/exasol/validation/GitHubPlatformValidatorTest.java
  src/test/java/com/exasol/validation/GitRepositoryValidatorTest.java
Labels: enhancement

#45 * #25: Added a validation report.
  doc/changes/changes_0.2.0.md
  doc/design.md
  doc/system_requirements.md
  pom.xml
  src/main/java/com/exasol/CredentialsProvider.java
  src/main/java/com/exasol/ReleaseRobot.java
  src/main/java/com/exasol/ReportWriter.java
  src/main/java/com/exasol/RepositoryHandler.java
  src/main/java/com/exasol/Runner.java
  src/main/java/com/exasol/UserInput.java
  src/main/java/com/exasol/repository/AbstractGitHubGitBranchContent.java
  src/main/java/com/exasol/repository/GitRepositoryException.java
  src/main/java/com/exasol/repository/maven/MavenPomParser.java
  src/main/java/com/exasol/validation/GitHubPlatformValidator.java
  src/main/java/com/exasol/validation/GitRepositoryValidator.java
  src/main/java/com/exasol/validation/PlatformValidatorFactory.java
  src/main/java/com/exasol/validation/ValidationReport.java
  src/main/java/com/exasol/validation/ValidationResult.java
  src/test/java/com/exasol/RepositoryHandlerTest.java
  src/test/java/com/exasol/UserInputTest.java
  src/test/java/com/exasol/github/AbstractGitHubGitBranchContentTest.java
  src/test/java/com/exasol/repository/maven/JavaMavenGitBranchContentTest.java
  src/test/java/com/exasol/validation/GitHubPlatformValidatorTest.java
  src/test/java/com/exasol/validation/GitRepositoryValidatorTest.java
  src/test/java/com/exasol/validation/PlatformValidatorFactoryTest.java
  src/test/java/com/exasol/validation/ValidationReportTest.java
Labels: feature

#51 #36: Added Maven release support.
  .github/workflows/dependencies_check.yml
  .github/workflows/maven_central_release.yml
  doc/changes/changes_0.2.0.md
  src/main/java/com/exasol/releaserobot/AbstractPlatform.java
  src/main/java/com/exasol/releaserobot/MavenPlatform.java
  src/main/java/com/exasol/releaserobot/Platform.java
  src/main/java/com/exasol/releaserobot/ReleaseRobot.java
  src/main/java/com/exasol/releaserobot/github/GitHubEntityFactory.java
  src/main/java/com/exasol/releaserobot/github/GitHubPlatform.java
  src/main/java/com/exasol/releaserobot/release/GitHubReleaseMaker.java
  src/main/java/com/exasol/releaserobot/release/MavenReleaseMaker.java
  src/main/java/com/exasol/releaserobot/release/ReleaseMakerFactory.java
  src/main/java/com/exasol/releaserobot/repository/maven/JavaMavenGitBranchContent.java
  src/main/java/com/exasol/releaserobot/validation/AbstractPlatformValidator.java
  src/main/java/com/exasol/releaserobot/validation/GitHubPlatformValidator.java
  src/main/java/com/exasol/releaserobot/validation/MavenPlatformValidator.java
  src/main/java/com/exasol/releaserobot/validation/PlatformValidatorFactory.java
  src/test/java/com/exasol/releaserobot/AbstractPlatformTest.java
  src/test/java/com/exasol/releaserobot/PlatformNameTest.java
  src/test/java/com/exasol/releaserobot/github/GitHubPlatformTest.java
  src/test/java/com/exasol/releaserobot/release/GitHubReleaseMakerTest.java
  src/test/java/com/exasol/releaserobot/release/MavenReleaseMakerTest.java
  src/test/java/com/exasol/releaserobot/release/ReleaseMakerFactoryTest.java
  src/test/java/com/exasol/releaserobot/validation/GitHubPlatformValidatorTest.java
  src/test/java/com/exasol/releaserobot/validation/PlatformValidatorFactoryTest.java
Labels: feature

#53 Extract GithubAPI
  .classpath
  .settings/org.eclipse.jdt.core.prefs
  doc/user_guide/user_guide.md
  pom.xml
  src/main/java/com/exasol/releaserobot/AbstractPlatform.java
  src/main/java/com/exasol/releaserobot/MavenPlatform.java
  src/main/java/com/exasol/releaserobot/Platform.java
  src/main/java/com/exasol/releaserobot/ReleaseRobot.java
  src/main/java/com/exasol/releaserobot/github/GitHubEntityFactory.java
  src/main/java/com/exasol/releaserobot/github/GitHubException.java
  src/main/java/com/exasol/releaserobot/github/GitHubPlatform.java
  src/main/java/com/exasol/releaserobot/github/GitHubRelease.java
  src/main/java/com/exasol/releaserobot/github/GithubAPIAdapter.java
  src/main/java/com/exasol/releaserobot/github/GithubGateway.java
  src/main/java/com/exasol/releaserobot/main/Runner.java
  src/main/java/com/exasol/releaserobot/release/GitHubReleaseMaker.java
  src/main/java/com/exasol/releaserobot/release/MavenReleaseMaker.java
  src/main/java/com/exasol/releaserobot/release/ReleaseMakerFactory.java
  src/main/java/com/exasol/releaserobot/repository/AbstractGitHubGitBranchContent.java
  src/main/java/com/exasol/releaserobot/repository/GitBranchContent.java
  src/main/java/com/exasol/releaserobot/repository/GitHubGitRepository.java
  src/main/java/com/exasol/releaserobot/validation/AbstractPlatformValidator.java
  src/test/java/com/exasol/releaserobot/AbstractPlatformTest.java
  src/test/java/com/exasol/releaserobot/RepositoryHandlerTest.java
  src/test/java/com/exasol/releaserobot/github/GitHubPlatformTest.java
  src/test/java/com/exasol/releaserobot/github/GitHubReleaseTest.java
  src/test/java/com/exasol/releaserobot/release/GitHubReleaseMakerTest.java
  src/test/java/com/exasol/releaserobot/release/MavenReleaseMakerTest.java
  src/test/java/com/exasol/releaserobot/repository/GitHubGitRepositoryTest.java
  src/test/java/com/exasol/releaserobot/validation/GitHubPlatformValidatorTest.java
Labels: refactoring
