Repository exasol/release-droid, pull requests merged in 2020-11, with the labels that each got.

#55 Extract release and validate usecases
  .settings/org.eclipse.jdt.core.prefs
  .settings/org.eclipse.jdt.ui.prefs
  pom.xml
  src/main/java/com/exasol/releaserobot/MavenPlatform.java
  src/main/java/com/exasol/releaserobot/Platform.java
  src/main/java/com/exasol/releaserobot/ReleaseInteractor.java
  src/main/java/com/exasol/releaserobot/ReleaseMaker.java
  src/main/java/com/exasol/releaserobot/ReleaseRobot.java
  src/main/java/com/exasol/releaserobot/ReleaseUseCase.java
  src/main/java/com/exasol/releaserobot/RepositoryHandler.java
  src/main/java/com/exasol/releaserobot/ValidateInteractor.java
  src/main/java/com/exasol/releaserobot/ValidateUseCase.java
  src/main/java/com/exasol/releaserobot/github/GitHubEntityFactory.java
  src/main/java/com/exasol/releaserobot/github/GitHubPlatform.java
  src/main/java/com/exasol/releaserobot/github/GithubGateway.java
  src/main/java/com/exasol/releaserobot/github/release/GitHubReleaseMaker.java
  src/main/java/com/exasol/releaserobot/main/Runner.java
  src/main/java/com/exasol/releaserobot/maven/MavenPlatform.java
  src/main/java/com/exasol/releaserobot/maven/release/MavenReleaseMaker.java
  src/main/java/com/exasol/releaserobot/release/GitHubReleaseMaker.java
  src/main/java/com/exasol/releaserobot/release/MavenReleaseMaker.java
  src/main/java/com/exasol/releaserobot/release/ReleaseMaker.java
  src/main/java/com/exasol/releaserobot/release/ReleaseMakerFactory.java
  src/main/java/com/exasol/releaserobot/repository/GitRepository.java
  src/test/java/com/exasol/releaserobot/RepositoryHandlerTest.java
  src/test/java/com/exasol/releaserobot/github/GitHubPlatformTest.java
  src/test/java/com/exasol/releaserobot/maven/MavenReleaseMakerTest.java
  src/test/java/com/exasol/releaserobot/release/GitHubReleaseMakerTest.java
  src/test/java/com/exasol/releaserobot/release/MavenReleaseMakerTest.java
  src/test/java/com/exasol/releaserobot/release/ReleaseMakerFactoryTest.java
Labels: refactoring

#56 #52: refactored ValidateInteractor
  src/main/java/com/exasol/releaserobot/AbstractPlatformValidator.java
  src/main/java/com/exasol/releaserobot/Platform.java
  src/main/java/com/exasol/releaserobot/PlatformName.java
  src/main/java/com/exasol/releaserobot/PlatformValidator.java
  src/main/java/com/exasol/releaserobot/ReleaseInteractor.java
  src/main/java/com/exasol/releaserobot/ReleaseUseCase.java
  src/main/java/com/exasol/releaserobot/RepositoryHandler.java
  src/main/java/com/exasol/releaserobot/UserInput.java
  src/main/java/com/exasol/releaserobot/ValidateInteractor.java
  src/main/java/com/exasol/releaserobot/ValidateUseCase.java
  src/main/java/com/exasol/releaserobot/github/GitHubEntityFactory.java
  src/main/java/com/exasol/releaserobot/github/GitHubPlatform.java
  src/main/java/com/exasol/releaserobot/github/GitHubPlatformValidator.java
  src/main/java/com/exasol/releaserobot/main/Runner.java
  src/main/java/com/exasol/releaserobot/maven/MavenPlatform.java
  src/main/java/com/exasol/releaserobot/maven/MavenPlatformValidator.java
  src/main/java/com/exasol/releaserobot/report/ReleaseReport.java
  src/main/java/com/exasol/releaserobot/report/ReleaseResult.java
  src/main/java/com/exasol/releaserobot/repository/GitRepositoryValidator.java
  src/main/java/com/exasol/releaserobot/validation/PlatformValidatorFactory.java
  src/test/java/com/exasol/releaserobot/PlatformNameTest.java
  src/test/java/com/exasol/releaserobot/RepositoryHandlerTest.java
  src/test/java/com/exasol/releaserobot/UserInputTest.java
  src/test/java/com/exasol/releaserobot/github/GitHubPlatformTest.java
  src/test/java/com/exasol/releaserobot/github/GitHubPlatformValidatorTest.java
  src/test/java/com/exasol/releaserobot/report/ReleaseReportTest.java
  src/test/java/com/exasol/releaserobot/report/ReportWriterTest.java
  src/test/java/com/exasol/releaserobot/repository/GitRepositoryValidatorTest.java
  src/test/java/com/exasol/releaserobot/validation/PlatformValidatorFactoryTest.java
Labels: refactoring

#57 #52: Refactored report
  src/main/java/com/exasol/releaserobot/ValidateUseCase.java
  src/main/java/com/exasol/releaserobot/github/GitHubEntityFactory.java
  src/main/java/com/exasol/releaserobot/github/GitHubPlatformValidator.java
  src/main/java/com/exasol/releaserobot/github/GitHubReleaseMaker.java
  src/main/java/com/exasol/releaserobot/main/ReleaseRobot.java
  src/main/java/com/exasol/releaserobot/main/Runner.java
  src/main/java/com/exasol/releaserobot/maven/MavenPlatformValidator.java
  src/main/java/com/exasol/releaserobot/maven/MavenReleaseMaker.java
  src/main/java/com/exasol/releaserobot/report/AbstractReport.java
  src/main/java/com/exasol/releaserobot/report/ReleaseReport.java
  src/main/java/com/exasol/releaserobot/report/Report.java
  src/main/java/com/exasol/releaserobot/report/ReportWriter.java
  src/main/java/com/exasol/releaserobot/report/ValidationReport.java
  src/main/java/com/exasol/releaserobot/repository/GitRepository.java
  src/main/java/com/exasol/releaserobot/repository/GitRepositoryValidator.java
  src/main/java/com/exasol/releaserobot/repository/ReleaseLetterParser.java
  src/main/java/com/exasol/releaserobot/usecases/AbstractResult.java
  src/main/java/com/exasol/releaserobot/usecases/CredentialsProvider.java
  src/main/java/com/exasol/releaserobot/usecases/Goal.java
  src/main/java/com/exasol/releaserobot/usecases/PlatformName.java
  src/main/java/com/exasol/releaserobot/usecases/ReleaseResult.java
  src/main/java/com/exasol/releaserobot/usecases/ReleaseRobotConstants.java
  src/main/java/com/exasol/releaserobot/usecases/Report.java
  src/main/java/com/exasol/releaserobot/usecases/ReportImpl.java
  src/main/java/com/exasol/releaserobot/usecases/Result.java
  src/main/java/com/exasol/releaserobot/usecases/UserInput.java
  src/main/java/com/exasol/releaserobot/usecases/ValidationResult.java
  src/main/java/com/exasol/releaserobot/usecases/release/ReleaseInteractor.java
  src/main/java/com/exasol/releaserobot/usecases/release/ReleaseMaker.java
  src/main/java/com/exasol/releaserobot/usecases/release/ReleaseUseCase.java
  src/main/java/com/exasol/releaserobot/usecases/validate/AbstractPlatformValidator.java
  src/main/java/com/exasol/releaserobot/usecases/validate/GitRepositoryValidator.java
  src/main/java/com/exasol/releaserobot/usecases/validate/PlatformValidator.java
  src/main/java/com/exasol/releaserobot/usecases/validate/ValidateInteractor.java
  src/main/java/com/exasol/releaserobot/usecases/validate/ValidateUseCase.java
  src/test/java/com/exasol/releaserobot/github/GitHubPlatformValidatorTest.java
  src/test/java/com/exasol/releaserobot/maven/MavenPlatformValidatorTest.java
  src/test/java/com/exasol/releaserobot/maven/MavenReleaseMakerTest.java
  src/test/java/com/exasol/releaserobot/report/ReleaseReportTest.java
  src/test/java/com/exasol/releaserobot/report/ReportWriterTest.java
  src/test/java/com/exasol/releaserobot/report/ValidationReportTest.java
  src/test/java/com/exasol/releaserobot/usecases/GoalTest.java
  src/test/java/com/exasol/releaserobot/usecases/PlatformNameTest.java
  src/test/java/com/exasol/releaserobot/usecases/UserInputTest.java
  src/test/java/com/exasol/releaserobot/usecases/validate/GitRepositoryValidatorTest.java
Labels: refactoring

#71 * #46: Separated pom parsing and validation.
  doc/changes/changes_0.2.0.md
  pom.xml
  src/main/java/com/exasol/releaserobot/github/GitHubPlatformValidator.java
  src/main/java/com/exasol/releaserobot/github/GitHubReleaseMaker.java
  src/main/java/com/exasol/releaserobot/main/Runner.java
  src/main/java/com/exasol/releaserobot/maven/MavenPlatformValidator.java
  src/main/java/com/exasol/releaserobot/maven/MavenRepositoryValidator.java
  src/main/java/com/exasol/releaserobot/repository/AbstractGitHubGitBranchContent.java
  src/main/java/com/exasol/releaserobot/repository/GitRepository.java
  src/main/java/com/exasol/releaserobot/repository/maven/JavaMavenGitBranchContent.java
  src/main/java/com/exasol/releaserobot/repository/maven/MavenPlugin.java
  src/main/java/com/exasol/releaserobot/repository/maven/MavenPom.java
  src/main/java/com/exasol/releaserobot/repository/maven/MavenPomParser.java
  src/main/java/com/exasol/releaserobot/usecases/ReportImpl.java
  src/main/java/com/exasol/releaserobot/usecases/release/ReleaseInteractor.java
  src/main/java/com/exasol/releaserobot/usecases/validate/AbstractPlatformValidator.java
  src/main/java/com/exasol/releaserobot/usecases/validate/GitRepositoryValidator.java
  src/main/java/com/exasol/releaserobot/usecases/validate/RepositoryValidator.java
  src/main/java/com/exasol/releaserobot/usecases/validate/ValidateInteractor.java
  src/test/java/com/exasol/releaserobot/maven/MavenRepositoryValidatorTest.java
  src/test/java/com/exasol/releaserobot/report/ReleaseReportTest.java
  src/test/java/com/exasol/releaserobot/report/ReportWriterTest.java
  src/test/java/com/exasol/releaserobot/repository/maven/JavaMavenGitBranchContentTest.java
  src/test/java/com/exasol/releaserobot/repository/maven/MavenPomParserTest.java
Labels: refactoring

#72 Refactoring/70 remove internal state dependencies
  doc/changes/changes_0.2.0.md
  src/main/java/com/exasol/releaserobot/github/GitHubEntityFactory.java
  src/main/java/com/exasol/releaserobot/github/GitHubPlatformValidator.java
  src/main/java/com/exasol/releaserobot/github/GitHubReleaseMaker.java
  src/main/java/com/exasol/releaserobot/github/GithubAPIAdapter.java
  src/main/java/com/exasol/releaserobot/github/GithubGateway.java
  src/main/java/com/exasol/releaserobot/github/GithubRepositoryGateway.java
  src/main/java/com/exasol/releaserobot/main/Runner.java
  src/main/java/com/exasol/releaserobot/maven/MavenPlatformValidator.java
  src/main/java/com/exasol/releaserobot/maven/MavenReleaseMaker.java
  src/main/java/com/exasol/releaserobot/maven/MavenRepositoryValidator.java
  src/main/java/com/exasol/releaserobot/repository/AbstractGitHubGitBranch.java
  src/main/java/com/exasol/releaserobot/repository/Branch.java
  src/main/java/com/exasol/releaserobot/repository/GitHubGitRepository.java
  src/main/java/com/exasol/releaserobot/repository/GitHubRepositoryContentFactory.java
  src/main/java/com/exasol/releaserobot/repository/GitRepository.java
  src/main/java/com/exasol/releaserobot/repository/Repository.java
  src/main/java/com/exasol/releaserobot/repository/maven/JavaMavenGitBranch.java
  src/main/java/com/exasol/releaserobot/usecases/release/ReleaseInteractor.java
  src/main/java/com/exasol/releaserobot/usecases/release/ReleaseMaker.java
  src/main/java/com/exasol/releaserobot/usecases/validate/AbstractPlatformValidator.java
  src/main/java/com/exasol/releaserobot/usecases/validate/GitRepositoryValidator.java
  src/main/java/com/exasol/releaserobot/usecases/validate/PlatformValidator.java
  src/main/java/com/exasol/releaserobot/usecases/validate/RepositoryGateway.java
  src/main/java/com/exasol/releaserobot/usecases/validate/RepositoryValidator.java
  src/main/java/com/exasol/releaserobot/usecases/validate/ValidateInteractor.java
  src/test/java/com/exasol/releaserobot/github/AbstractGitHubGitBranchTest.java
  src/test/java/com/exasol/releaserobot/github/GitHubPlatformValidatorTest.java
  src/test/java/com/exasol/releaserobot/maven/MavenPlatformValidatorTest.java
  src/test/java/com/exasol/releaserobot/maven/MavenReleaseMakerTest.java
  src/test/java/com/exasol/releaserobot/maven/MavenRepositoryValidatorTest.java
  src/test/java/com/exasol/releaserobot/repository/GitHubGitRepositoryTest.java
  src/test/java/com/exasol/releaserobot/repository/maven/JavaMavenGitBranchContentTest.java
  src/test/java/com/exasol/releaserobot/usecases/validate/GitRepositoryValidatorTest.java
Labels: refactoring

#73 * #54: Added check from an HTTP response from the Github when trigger…
  doc/changes/changes_0.2.0.md
  src/main/java/com/exasol/releaserobot/github/GithubAPIAdapter.java
Labels: enhancement

#75 Refactoring/74 refactor GitHub api adapter
  doc/changes/changes_0.2.0.md
  src/main/java/com/exasol/releaserobot/github/GitHubPlatformValidator.java
  src/main/java/com/exasol/releaserobot/github/GitHubRelease.java
  src/main/java/com/exasol/releaserobot/github/GitHubReleaseMaker.java
  src/main/java/com/exasol/releaserobot/github/GithubAPIAdapter.java
  src/main/java/com/exasol/releaserobot/github/GithubGateway.java
  src/main/java/com/exasol/releaserobot/github/GithubRepositoryGateway.java
  src/main/java/com/exasol/releaserobot/main/ReleaseRobot.java
  src/main/java/com/exasol/releaserobot/main/Runner.java
  src/main/java/com/exasol/releaserobot/maven/MavenPlatformValidator.java
  src/main/java/com/exasol/releaserobot/maven/MavenReleaseMaker.java
  src/main/java/com/exasol/releaserobot/maven/MavenRepositoryValidator.java
  src/main/java/com/exasol/releaserobot/report/ReportWriter.java
  src/main/java/com/exasol/releaserobot/repository/AbstractGitHubGitBranch.java
  src/main/java/com/exasol/releaserobot/repository/Branch.java
  src/main/java/com/exasol/releaserobot/repository/GitHubGitRepository.java
  src/main/java/com/exasol/releaserobot/repository/Repository.java
  src/main/java/com/exasol/releaserobot/repository/maven/MavenRepository.java
  src/main/java/com/exasol/releaserobot/usecases/Repository.java
  src/main/java/com/exasol/releaserobot/usecases/UserInput.java
  src/main/java/com/exasol/releaserobot/usecases/release/ReleaseInteractor.java
  src/main/java/com/exasol/releaserobot/usecases/release/ReleaseMaker.java
  src/main/java/com/exasol/releaserobot/usecases/release/ReleaseUseCase.java
  src/main/java/com/exasol/releaserobot/usecases/validate/AbstractPlatformValidator.java
  src/main/java/com/exasol/releaserobot/usecases/validate/GitRepositoryValidator.java
  src/main/java/com/exasol/releaserobot/usecases/validate/PlatformValidator.java
  src/main/java/com/exasol/releaserobot/usecases/validate/RepositoryGateway.java
  src/main/java/com/exasol/releaserobot/usecases/validate/RepositoryValidator.java
  src/main/java/com/exasol/releaserobot/usecases/validate/ValidateInteractor.java
  src/main/java/com/exasol/releaserobot/usecases/validate/ValidateUseCase.java
  src/test/java/com/exasol/releaserobot/github/AbstractRepositoryTest.java
  src/test/java/com/exasol/releaserobot/github/GitHubPlatformValidatorTest.java
  src/test/java/com/exasol/releaserobot/maven/MavenPlatformValidatorTest.java
  src/test/java/com/exasol/releaserobot/maven/MavenReleaseMakerTest.java
  src/test/java/com/exasol/releaserobot/maven/MavenRepositoryValidatorTest.java
  src/test/java/com/exasol/releaserobot/repository/GitHubGitRepositoryTest.java
  src/test/java/com/exasol/releaserobot/repository/maven/MavenRepositoryTest.java
  src/test/java/com/exasol/releaserobot/usecases/UserInputTest.java
  src/test/java/com/exasol/releaserobot/usecases/validate/GitRepositoryValidatorTest.java
Labels: refactoring

#78 * #68: Extracted UserInput parsing.
  doc/changes/changes_0.2.0.md
  src/main/java/com/exasol/releaserobot/github/GithubRepositoryGateway.java
  src/main/java/com/exasol/releaserobot/main/Runner.java
  src/main/java/com/exasol/releaserobot/main/UserInputParser.java
  src/main/java/com/exasol/releaserobot/report/ReportWriter.java
  src/main/java/com/exasol/releaserobot/usecases/UserInput.java
  src/main/java/com/exasol/releaserobot/usecases/release/ReleaseInteractor.java
  src/test/java/com/exasol/releaserobot/main/UserInputParserTest.java
  src/test/java/com/exasol/releaserobot/report/ReportWriterTest.java
  src/test/java/com/exasol/releaserobot/usecases/UserInputTest.java
Labels: refactoring

#79 Refactoring/59 remove duplication code in main
  doc/changes/changes_0.2.0.md
  src/main/java/com/exasol/releaserobot/main/ReleaseRobot.java
  src/main/java/com/exasol/releaserobot/main/Runner.java
  src/main/java/com/exasol/releaserobot/usecases/PlatformName.java
  src/main/java/com/exasol/releaserobot/usecases/ReleasablePlatform.java
  src/main/java/com/exasol/releaserobot/usecases/release/ReleaseInteractor.java
  src/main/java/com/exasol/releaserobot/usecases/release/ReleaseUseCase.java
  src/main/java/com/exasol/releaserobot/usecases/validate/ValidateInteractor.java
  src/test/java/com/exasol/releaserobot/usecases/PlatformNameTest.java
Labels: refactoring

#80 Feature/50 add validations for maven release
  doc/changes/changes_0.2.0.md
  doc/user_guide/github_release_template.md
  doc/user_guide/maven_central_release_pom_file_template.md
  doc/user_guide/maven_central_release_template.md
  doc/user_guide/user_guide.md
  src/main/java/com/exasol/releaserobot/maven/MavenPlatformValidator.java
  src/main/java/com/exasol/releaserobot/repository/maven/MavenPlugin.java
  src/main/java/com/exasol/releaserobot/repository/maven/MavenPomParser.java
  src/test/java/com/exasol/releaserobot/github/AbstractRepositoryTest.java
  src/test/java/com/exasol/releaserobot/maven/MavenPlatformValidatorTest.java
  src/test/java/com/exasol/releaserobot/repository/maven/MavenPomParserTest.java
  src/test/java/com/exasol/releaserobot/repository/maven/MavenRepositoryTest.java
Labels: feature

#83 #81: Fixed requirements tracing.
  doc/changes/changes_0.2.0.md
  doc/design.md
  doc/system_requirements.md
  pom.xml
  src/main/java/com/exasol/releaserobot/github/GitHubPlatformValidator.java
  src/main/java/com/exasol/releaserobot/github/GitHubReleaseMaker.java
  src/main/java/com/exasol/releaserobot/main/ReleaseRobot.java
  src/main/java/com/exasol/releaserobot/maven/MavenPlatformValidator.java
  src/main/java/com/exasol/releaserobot/maven/MavenReleaseMaker.java
  src/main/java/com/exasol/releaserobot/repository/maven/MavenRepository.java
  src/main/java/com/exasol/releaserobot/usecases/Repository.java
  src/main/java/com/exasol/releaserobot/usecases/release/ReleaseInteractor.java
  src/main/java/com/exasol/releaserobot/usecases/validate/ValidateInteractor.java
  src/main/java/com/exasol/releaserobot/usecases/validate/ValidateUseCase.java
  src/test/java/com/exasol/releaserobot/github/AbstractRepositoryTest.java
  src/test/java/com/exasol/releaserobot/github/GitHubPlatformValidatorTest.java
  src/test/java/com/exasol/releaserobot/maven/MavenPlatformValidatorTest.java
  src/test/java/com/exasol/releaserobot/maven/MavenReleaseMakerTest.java
  src/test/java/com/exasol/releaserobot/repository/maven/MavenRepositoryTest.java
Labels: documentation, refactoring

#84 #76: Removed GitHubException from usecases.
  doc/changes/changelog.md
  doc/changes/changes_0.2.1.md
  pom.xml
  src/main/java/com/exasol/releaserobot/github/GitHubReleaseMaker.java
  src/main/java/com/exasol/releaserobot/github/GithubAPIAdapter.java
  src/main/java/com/exasol/releaserobot/github/GithubRepositoryGateway.java
  src/main/java/com/exasol/releaserobot/main/ReleaseRobot.java
  src/main/java/com/exasol/releaserobot/main/Runner.java
  src/main/java/com/exasol/releaserobot/maven/MavenReleaseMaker.java
  src/main/java/com/exasol/releaserobot/repository/GitRepositoryException.java
  src/main/java/com/exasol/releaserobot/repository/RepositoryException.java
  src/main/java/com/exasol/releaserobot/repository/maven/MavenPomParser.java
  src/main/java/com/exasol/releaserobot/repository/maven/MavenRepository.java
  src/main/java/com/exasol/releaserobot/usecases/ReleasablePlatform.java
  src/main/java/com/exasol/releaserobot/usecases/ReleaseException.java
  src/main/java/com/exasol/releaserobot/usecases/Repository.java
  src/main/java/com/exasol/releaserobot/usecases/release/ReleaseInteractor.java
  src/main/java/com/exasol/releaserobot/usecases/release/ReleaseMaker.java
  src/main/java/com/exasol/releaserobot/usecases/release/ReleaseUseCase.java
  src/main/java/com/exasol/releaserobot/usecases/validate/AbstractPlatformValidator.java
  src/main/java/com/exasol/releaserobot/usecases/validate/RepositoryGateway.java
  src/main/java/com/exasol/releaserobot/usecases/validate/ValidateInteractor.java
  src/main/java/com/exasol/releaserobot/usecases/validate/ValidateUseCase.java
  src/test/java/com/exasol/releaserobot/github/AbstractRepositoryTest.java
  src/test/java/com/exasol/releaserobot/github/GitHubPlatformValidatorTest.java
  src/test/java/com/exasol/releaserobot/maven/MavenPlatformValidatorTest.java
  src/test/java/com/exasol/releaserobot/maven/MavenReleaseMakerTest.java
  src/test/java/com/exasol/releaserobot/repository/maven/MavenRepositoryTest.java
Labels: refactoring

#93 #90: Improved the changes file template.
  doc/changes/changes_0.2.1.md
  doc/user_guide/changes_file_template.md
Labels: documentation

#95 * #86: Added support for ${project.version} property while detecting …
  doc/changes/changes_0.2.1.md
  src/main/java/com/exasol/releasedroid/repository/maven/MavenRepository.java
  src/test/java/com/exasol/releasedroid/repository/maven/MavenRepositoryTest.java
Labels: enhancement

#94 * #91: Improved console logging output.
  doc/changes/changes_0.2.1.md
  doc/user_guide/user_guide.md
  src/main/java/com/exasol/releasedroid/github/GitHubPlatformValidator.java
  src/main/java/com/exasol/releasedroid/main/ReleaseDroidFormatter.java
  src/main/java/com/exasol/releasedroid/main/ReportLogger.java
  src/main/java/com/exasol/releasedroid/main/Runner.java
  src/main/java/com/exasol/releasedroid/usecases/release/ReleaseInteractor.java
  src/main/java/com/exasol/releasedroid/usecases/validate/GitRepositoryValidator.java
  src/main/java/com/exasol/releasedroid/usecases/validate/ValidateInteractor.java
  src/main/resources/logging.properties
Labels: enhancement

#96 #89: Fix false positive validation for open ticket
  doc/changes/changes_0.2.1.md
  src/main/java/com/exasol/releasedroid/repository/ReleaseLetterParser.java
  src/test/java/com/exasol/releasedroid/repository/ReleaseLetterParserTest.java
Labels: bug
