Repository exasol/release-droid, pull requests merged in 2021-03, with the labels that each got.

#125 bug/124: Fixed a wrong error message
  doc/changes/changes_0.4.0.md
  src/main/java/com/exasol/releasedroid/repository/LocalRepositoryGate.java
Labels: bug

#129 Refactoring/128 change release strategy for scala repositories
  .github/workflows/github_release.yml
  .github/workflows/prepare_original_checksum.yml
  .github/workflows/print_quick_checksum.yml
  doc/design.md
  doc/error_codes.md
  doc/user_guide/github_release_template.md
  doc/user_guide/templates/changes_file_template.md
  doc/user_guide/templates/github_release_template.md
  doc/user_guide/templates/maven_central_release_pom_file_template.md
  doc/user_guide/templates/maven_central_release_template.md
  doc/user_guide/templates/prepare_original_checksum_template.md
  doc/user_guide/templates/print_quick_checksum_template.md
  doc/user_guide/templates/sbt_file_template.md
  doc/user_guide/user_guide.md
  pom.xml
  src/main/java/com/exasol/releasedroid/github/GitHubPlatformValidator.java
  src/main/java/com/exasol/releasedroid/main/UserInputParser.java
  src/main/java/com/exasol/releasedroid/maven/MavenPlatformValidator.java
  src/main/java/com/exasol/releasedroid/repository/JavaRepository.java
  src/main/java/com/exasol/releasedroid/repository/RepositoryFactory.java
  src/main/java/com/exasol/releasedroid/repository/ScalaRepository.java
  src/main/java/com/exasol/releasedroid/usecases/Goal.java
  src/main/java/com/exasol/releasedroid/usecases/Language.java
  src/main/java/com/exasol/releasedroid/usecases/Repository.java
  src/main/java/com/exasol/releasedroid/usecases/UserInput.java
  src/main/java/com/exasol/releasedroid/usecases/validate/AbstractRepositoryValidator.java
  src/main/java/com/exasol/releasedroid/usecases/validate/GitRepositoryValidator.java
  src/main/java/com/exasol/releasedroid/usecases/validate/ScalaRepositoryValidator.java
  src/test/java/com/exasol/releasedroid/main/ReportWriterTest.java
  src/test/java/com/exasol/releasedroid/main/UserInputParserTest.java
  src/test/java/com/exasol/releasedroid/repository/BaseRepositoryTest.java
  src/test/java/com/exasol/releasedroid/repository/JavaRepositoryTest.java
  src/test/java/com/exasol/releasedroid/repository/RepositoryFactoryTest.java
  src/test/java/com/exasol/releasedroid/repository/ScalaRepositoryTest.java
  src/test/java/com/exasol/releasedroid/usecases/LanguageTest.java
  src/test/java/com/exasol/releasedroid/usecases/UserInputTest.java
  src/test/java/com/exasol/releasedroid/usecases/validate/GitRepositoryValidatorTest.java
  src/test/java/com/exasol/releasedroid/usecases/validate/ScalaRepositoryValidatorTest.java
Labels: refactoring

#130 * #119: Removed maven plugin validation
  doc/changes/changes_0.4.0.md
  pom.xml
  src/main/java/com/exasol/releasedroid/maven/JavaRepositoryValidator.java
  src/main/java/com/exasol/releasedroid/maven/MavenPlatformValidator.java
  src/main/java/com/exasol/releasedroid/maven/MavenPluginValidator.java
  src/main/java/com/exasol/releasedroid/repository/MavenPlugin.java
  src/main/java/com/exasol/releasedroid/repository/MavenPom.java
  src/main/java/com/exasol/releasedroid/repository/MavenPomParser.java
  src/main/java/com/exasol/releasedroid/repository/ReleaseLetterParser.java
  src/test/java/com/exasol/releasedroid/maven/JavaRepositoryValidatorTest.java
  src/test/java/com/exasol/releasedroid/maven/MavenPlatformValidatorTest.java
  src/test/java/com/exasol/releasedroid/repository/MavenPomParserTest.java
  src/test/java/com/exasol/releasedroid/repository/ReleaseLetterParserTest.java
Labels: bug, refactoring

#133 * #132: Renamed the workflow scripts.
  .github/workflows/release_droid_prepare_original_checksum.yml
  .github/workflows/release_droid_print_quick_checksum.yml
  .github/workflows/release_droid_upload_github_release_assets.yml
  doc/changes/changes_0.4.0.md
  doc/design.md
  doc/user_guide/templates/prepare_original_checksum_template.md
  doc/user_guide/templates/print_quick_checksum_template.md
  doc/user_guide/templates/release_on_maven_central_template.md
  doc/user_guide/templates/upload_github_release_assets_template.md
  doc/user_guide/user_guide.md
  src/main/java/com/exasol/releasedroid/github/GitHubPlatformValidator.java
  src/main/java/com/exasol/releasedroid/github/GithubAPIAdapter.java
  src/main/java/com/exasol/releasedroid/usecases/validate/GitRepositoryValidator.java
Labels: refactoring

#135 * #134: Fixed parsing of the plugins in the pom file.
  doc/changes/changes_0.4.0.md
  src/main/java/com/exasol/releasedroid/maven/MavenPluginValidator.java
  src/main/java/com/exasol/releasedroid/repository/MavenPlugin.java
  src/main/java/com/exasol/releasedroid/repository/MavenPomParser.java
  src/test/java/com/exasol/releasedroid/maven/MavenPlatformValidatorTest.java
  src/test/java/com/exasol/releasedroid/repository/MavenPomParserTest.java
Labels: bug

#137 * #136: Excluded `project-keeper-maven-plugin` from the version validation
  doc/changes/changes_0.4.0.md
  doc/design.md
  src/main/java/com/exasol/releasedroid/maven/JavaRepositoryValidator.java
  src/main/java/com/exasol/releasedroid/maven/MavenPlatformValidator.java
  src/main/java/com/exasol/releasedroid/maven/MavenReleaseMaker.java
  src/test/java/com/exasol/releasedroid/maven/JavaRepositoryValidatorTest.java
  src/test/java/com/exasol/releasedroid/maven/MavenPlatformValidatorTest.java
  src/test/java/com/exasol/releasedroid/maven/MavenReleaseMakerTest.java
Labels: bug
